spring:
  application:
    name: grpc-example

grpc:
  server:
    port: 9090
  client:
    grpc-server:
      address: static://localhost:9090
      negotiation-type: plaintext

logging:
  level:
    com.jinloes.grpc: INFO
    net.devh.boot.grpc: DEBUG